import {StyleSheet} from 'react-native';

export const cartStyles = () => {
    return StyleSheet.create({
        card: {
            backgroundColor: "#FAF7F0",
            width: "100%",
            height: 225,
            borderWidth: 1,
            borderColor: "rgba(0,0,0,0.2)",
            borderRadius: 10,
            shadowColor: "#000000",
            shadowOpacity: 0.5,
            shadowOffset: {width: 0, height: 2},
            elevation: 3,
        },
        cardContainer: {
            flexDirection: "row",
            justifyContent: "flex-start",
            alignItems: "center",
            width: "100%",
            gap: 1,
            height: "80%",
        },
        cartImage: {
            width: "40%",
            height: "80%",
            marginLeft: 10,
            borderRadius: 10,
        },
        headerText: {
            fontSize: 18,
            fontWeight: "bold",
            marginTop: 5,
            marginLeft: 12,
            marginBottom: 5,
        },
        quantityButtons: {
            backgroundColor:"#FFEB91",
            borderColor: "#FDE681",
            borderRadius: 50,
            width: "32%",
            height: "100%",
            alignItems: "center",
            justifyContent: "center",
        },
        quantityButtonText: {
            fontSize: 18,
            marginLeft: 5,
            textAlign: "center",
            fontWeight: "bold",
        },
        quantityContainer: {
            flexDirection: "row",
            alignItems: "center",
            borderWidth: 1,
            borderColor: "rgba(0,0,0,0.2)",
            justifyContent: "space-between",
            borderRadius: 50,
            height: "20%",
            width: "60%",
            backgroundColor: "#91CAFF",
        },
        dropdown: {
            height: 30,
            width: "93%",
            borderWidth: 1,
            borderColor: "rgba(0,0,0,0.2)",
            marginBottom: 5,
            borderRadius: 5,
        },
        cartInfoContainer: {
            width: "44%",
            height: "85%",
            marginLeft: 10,
            marginTop: 20,
        },
        checkbox: {
            borderRadius: 5,
            marginLeft: 5,
            marginTop: 7,
        },
        checkOutButton: {
            width: "30%",
            borderWidth: 1,
            borderColor: "#FDE681",
            padding: 10,
            borderRadius: 20,
            backgroundColor:"#FFEB91",
            alignItems: "center",
            marginRight: 25,
        },
        bottomTab: {
            position: "absolute",
            bottom: 0,
            left: 0,
            right: 0,
            height: 70,
            backgroundColor: "#eee",
            borderTopWidth: 1,
            borderColor: "#ccc",
            alignItems: "center",
            justifyContent: "flex-end",
            flexDirection: "row",
        }
    })
}